# This rule is not used by the project swap-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the node-swap.openshift.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: swap-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodeswap-editor-role
rules:
- apiGroups:
  - node-swap.openshift.io
  resources:
  - nodeswaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node-swap.openshift.io
  resources:
  - nodeswaps/status
  verbs:
  - get
